import Head from 'next/head'
import Header from '../components/Header';
import MainContent from '../components/MainContent';
import Footer from '../components/Footer';

export default function Home({ cryptoData }) {

  console.log(cryptoData);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Inter:wght@300;400;600;700&family=Josefin+Sans&family=Poppins:wght@300&display=swap" rel="stylesheet" />
      </Head>
      <main className="main">
        <Header cryptoData={cryptoData} />
        <MainContent />
        <Footer />
      </main>
    </>
  )
}

export async function getServerSideProps() {

  const fetchCryptos = async () => {
    const response = await fetch("https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&order=market_cap_desc&per_page=50&page=1&sparkline=false");
    const data = await response.json();

    if (!response.ok) {
      throw new Error("Something went wrong...");
    }

    return data;
  }

  try {
    const cryptoData = await fetchCryptos();
    return {
      props: {
        cryptoData
      },
    }
  }
  catch (err) {
    console.log(err.message);
  }

}
